language: android

android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28
    - platform-tools

jdk:
  - oraclejdk8

script: ./gradlew clean build test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)