language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
    - tools
    - platform-tools

  licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"

script: ./gradlew clean build test jacocoTestReport

after_success: bash <(curl -s https://codecov.io/bash)