language: android
dist: trusty
android:
  components:
    # The BuildTools version used by your project
    - build-tools-30.0.3

    # The SDK version used to compile your project
    - android-30

  licenses:
    - 'android-sdk-license-.+'

script: ./gradlew clean build test jacocoTestReport

after_success: bash <(curl -s https://codecov.io/bash)