name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '17'
            java-package: jdk
            
      - name: Create google-services
        run: touch ./app/google-services.json | base64
        
      - name: Create local.properties
        run: touch ./local-properties | base64
        
      - name: Putting data inside google-services
        env: 
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > ./app/google-services.json
        
      - name: Putting data inside local.properties
        env: 
          DATA: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo $DATA > ./local.properties

      - name: Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with: 
            api-level: 29
            script: ./gradlew connectedCheck jacocoTestReport

      - name: Generate report
        uses: actions/upload-artifact@v2
        with:
          name: report 
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Download Test Report Folder
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Upload Test Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,libraries/core/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,features/regional_live/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
